spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: test
    password: password
    driverClassName: org.h2.Driver
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


