spring:
  output:
  ansi:
    enabled: ALWAYS
  logging:
    level:
      root: ERROR
      org.springframework.web: ERROR
      com.demo: DEBUG
      org.hibernate: ERROR

  datasource:
    url: jdbc:h2:mem:mydb
    username: test
    password: password
    driverClassName: org.h2.Driver
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect